openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API'
  description: gwr oeifjwrifj
paths:
  /space/:
    get:
      parameters:
      - name: fwrzofiroi
        in: header
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      - name: Update
        in: header
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      - name: abcheader
        in: header
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      - name: cdf
        in: query
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      summary: New update check
      responses:
        '200': 
          description: Update spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '400': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '500': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '404': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id: 
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: number
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: number
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
  