openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Sample API here'
  description: Buy or rent spacecrafts her wdd updated
paths:
  /space/:
    get:
      parameters:
      - name: qefwrf
        in: header
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      - name: abcheaderchanged
        in: header
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      - name: cdf
        in: query
        description: your API key
        required: true
        explode: false
        schema:
          type: string
      summary: Changing now now realtim
      responses:
        '200': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '201':
          description: These spacecraft corresponding to the ssss provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No spacecraft found for the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: POSTdfdf aaaa spacecraft hsssere again now now
      responses:
        '200': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '201':
          description: These spacecraft corresponding to the ssss provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
    put:
      summary: POST aaaa spacecraft hsssere again now now
      responses:
        '200': 
          description: These spacecraft corresponding to the provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        '201':
          description: These spacecraft corresponding to the ssss provided `spacecraftId`
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
components:
  schemas:
    SpacecraftId:
      description: The unique identifier of a spacecraft
      type: string
    Spacecraft:
      type: object
      required:
        - id
        - name
        - type
      properties:
        id:
          $ref: '#/components/schemas/SpacecraftId'
        name:
          type: number
        type:
          type: string
          enum:
            - capsule
            - probe
            - satellite
            - spaceplane
            - station
        description:
          type: number
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []
  